### ISSUE TITLE
When concatenating videos, the output is stretched out.

### ISSUE THREAD

**Issue by bman46** [tomaszzmuda/Xabe.FFmpeg#203] opened 2019-12-08 21:25 UTC
When I concatenate about 30x 2 second videos from the same camera, it results in a stretched out version of the video (see attached images).
**Code:**
`IConversionResult result = Conversion.Concatenate(output, names.ToArray()).Result;` 
(`names` contains the path and name of the video files as a single string)
**Input:**
![input](https://user-images.githubusercontent.com/10489031/70396445-12a9c380-19d7-11ea-9e40-75120701a968.PNG)
**Result:**
![Output](https://user-images.githubusercontent.com/10489031/70396446-12a9c380-19d7-11ea-9bdb-d8308e8f4a34.PNG)

**Comment by tomaszzmuda** [comment] 2019-12-14 18:22
Hello @bman46 
I tried to figure out what's happened with this video but cannot reproduce this issue.
Are you sure that every video has the same dimension? It is possible to upload these videos?

**Comment by bman46** [comment] 2019-12-15 01:31
Hi, I think that they are all the same size as the command `ffmpeg -f concat -safe 0 -i list.txt output.mp4` works as expected without any issues in the resulting video. Attached is a zip file with all of the videos.
[Videos.zip](https://github.com/tomaszzmuda/Xabe.FFmpeg/files/3964527/Videos.zip)

**Comment by tomaszzmuda** [comment] 2019-12-15 11:41
`var files = Directory.GetFiles(@"C:\Users\tzmuda\Downloads\Videos");
 string output = Path.ChangeExtension(Path.GetTempFileName(), FileExtensions.Mp4);

IConversionResult result = await Conversion.Concatenate(output, files).ConfigureAwait(false);`

I run this code with all files you uploaded and it's perfectly fine. 
![image](https://user-images.githubusercontent.com/13612984/70862100-032afd00-1f38-11ea-9017-7c11a7cff469.png)

Can you pass arguments from IConversionResult directly to ffmpeg?

**Comment by bman46** [comment] 2019-12-15 16:33
Interesting, if you would like to check out my code, [here is the repo](https://github.com/bman46/Unifi-Video-Downloader). The method im using to concatenate the videos for this library is the last method the the [VideoProcessing class](https://github.com/bman46/Unifi-Video-Downloader/blob/master/Bulk%20UFV%20Downloader/VideoProcessing.cs). Also, i'm not sure exactly what you mean by passing the arguments directly to ffmpeg but attached is the result of `IConversionResult.Arguments`. [Arguments.txt](https://github.com/tomaszzmuda/Xabe.FFmpeg/files/3965140/Arguments.txt)
Also, i was unable to upload the resulting video as it was ~75MB while the files used to make the video totaled ~22MB.

**Comment by tomaszzmuda** [comment] 2019-12-18 19:28
Still cannot reproduce this ;/

I mean to do this:
ffmpeg.exe -n -threads 8 -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741597664_1575741599664_1575574425398_167201381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741599671_1575741601671_1575574425398_167203381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741601671_1575741603671_1575574425398_167205381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741603671_1575741605671_1575574425398_167207381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741605671_1575741607671_1575574425398_167209381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741607671_1575741609671_1575574425398_167211381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741609671_1575741611671_1575574425398_167213381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741611671_1575741613671_1575574425398_167215381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741613671_1575741615671_1575574425398_167217381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741615671_1575741617671_1575574425398_167219381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741617671_1575741619671_1575574425398_167221381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741619671_1575741621671_1575574425398_167223381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741621671_1575741623671_1575574425398_167225381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741623671_1575741625671_1575574425398_167227381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741625671_1575741627671_1575574425398_167229381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741627664_1575741629664_1575574425398_167231381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741629671_1575741631671_1575574425398_167233381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741631670_1575741633670_1575574425398_167235381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741633671_1575741635671_1575574425398_167237381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741635671_1575741637671_1575574425398_167239381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741637671_1575741639671_1575574425398_167241381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741639671_1575741641671_1575574425398_167243381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741641671_1575741643671_1575574425398_167245381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741643670_1575741645670_1575574425398_167247381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741645669_1575741647669_1575574425398_167249381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741647668_1575741649668_1575574425398_167251381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741649667_1575741651667_1575574425398_167253381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741651667_1575741653667_1575574425398_167255381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741653667_1575741655667_1575574425398_167257381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741655667_1575741657667_1575574425398_167259381.mp4" -i "C:\Users\brend\AppData\Local\Temp\VideoFiles1576423218\1575741657660_1575741659660_1575574425398_167261381.mp4" -t 1 -f lavfi -i anullsrc=r=48000:cl=stereo -filter_complex " [0:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v0]; [1:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v1]; [2:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v2]; [3:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v3]; [4:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v4]; [5:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v5]; [6:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v6]; [7:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v7]; [8:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v8]; [9:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v9]; [10:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v10]; [11:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v11]; [12:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v12]; [13:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v13]; [14:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v14]; [15:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v15]; [16:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v16]; [17:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v17]; [18:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v18]; [19:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v19]; [20:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v20]; [21:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v21]; [22:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v22]; [23:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v23]; [24:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v24]; [25:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v25]; [26:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v26]; [27:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v27]; [28:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v28]; [29:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v29]; [30:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v30]; [v0][0:a] [v1][1:a] [v2][2:a] [v3][3:a] [v4][4:a] [v5][5:a] [v6][6:a] [v7][7:a] [v8][8:a] [v9][9:a] [v10][10:a] [v11][11:a] [v12][12:a] [v13][13:a] [v14][14:a] [v15][15:a] [v16][16:a] [v17][17:a] [v18][18:a] [v19][19:a] [v20][20:a] [v21][21:a] [v22][22:a] [v23][23:a] [v24][24:a] [v25][25:a] [v26][26:a] [v27][27:a] [v28][28:a] [v29][29:a] [v30][30:a] concat=n=31:v=1:a=1 [v] [a]" -map "[v]" -map "[a]" "C:\Users\brend\Desktop\out\out.mp4"

In powershell and look at result. Maybe it depends of ffmpeg.exe version

**Comment by bman46** [comment] 2019-12-27 17:08
Just ran that command and i still get the same output so it seems to be a issue with FFMpeg. I am using version 4.2.1.

**Comment by tomaszzmuda** [comment] 2020-01-02 19:06
Tried to do fix this somehow but cannot reproduce this issue. Closing this due to it's problem with ffmpeg not the library itself.

**Comment by bman46** [comment] 2020-01-02 19:07
Ok, thanks for you help.

**Comment by Dxesto** [comment] 2020-01-05 20:56
How you fixed it ?

**Comment by bman46** [comment] 2020-01-05 21:13
@Dxesto I did not fix it. I just wrote a workaround in my code that deals with ffmpeg directly without using this repo. Are you also having this issue?

**Comment by Dxesto** [comment] 2020-01-05 21:28
Yes. I also have this issue. I tried use older version of FFmpeg but it did not help me. So If you can, could  you please share your workaround  with me. Thank you.

**Comment by bman46** [comment] 2020-01-05 21:38
Check out the video processing class in my repo ( https://github.com/bman46/Unifi-Video-Downloader/blob/master/Bulk%20UFV%20Downloader/VideoProcessing.cs ) don’t use the overloaded Concatnate method with the Boolean as it was for testing this repo.

**Comment by M4jx** [comment] 2020-02-23 17:28
Same here, the command posted above produces the same results as `Conversion.Concatenate`.
However `ffmpeg -f concat -safe 0 -i list.txt` produces output with correct scale.

**Comment by M4jx** [comment] 2020-02-23 18:11
Solved by specifying the `-aspect 16/9` flag to the command.

Final working command:

`ffmpeg.exe -n -threads 8 -i 1.mp4 -i 2.mp4 -i 3.mp4 -t 1 -f lavfi  -i anullsrc=r=48000:cl=stereo -filter_complex " [0:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v0]; [1:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v1]; [2:v]scale=1920:1080,setdar=dar=16:9,setpts=PTS-STARTPTS[v2]; [v0][0:a] [v1][1:a] [v2][2:a] concat=n=3:v=1:a=1 [v] [a]" -map "[v]" -map "[a]" -aspect 16/9 "out.mp4"`

**Comment by tomaszzmuda** [comment] 2020-02-23 18:14
Great!
I'm going to add aspect to Concatenate method.
Thanks for sharing solution :)

**Comment by tomaszzmuda** [comment] 2020-02-26 08:34
Fixed in #229 
New version on nuget will be available in a few days.

**Closed by tomaszzmuda** 2020-02-26 08:34 UTC
